sudo: required

language: python

branches: # choose which barnch to build
  only:
    - master

matrix: # parallel verify different python version 
  include:
    - python: 2.7
      env: docker_image=2.7.14-alpine3.7

    - python: 3.7-dev
      env: docker_image=3.7-rc-alpine

services: # use docker for artifact
  - docker

install:
 - pip install --upgrade pip # update pip version if not latest
 - pip install pyflakes 
 - pip install pylint 

before_script:
 - pyflakes . # static code analyze
 - pylint sample.py --disable=missing-docstring # Coding style check

script: python test_sample.py # run unit test

after_success:
 - docker pull python:$docker_image
 - docker images
 - envsubst < Dockerfile.template > Dockerfile
 - docker build -t my_python:$docker_image .  
 - docker images  

