sudo: required

language: python

branches: # choose which barnch to build
  only:
    - master

matrix: # parallel verify different python version 
  include:
    - python: 2.7
      env: docker_image=2.7.14-alpine3.7

    - python: 3.7-dev
      env: docker_image=3.7-rc-alpine

services: # use docker for artifact
  - docker

# Prepare build and test environment
install:
 #- pip install -r /path/to/requirements.txt # install packages from file
 - pip install --upgrade pip # update pip version if not latest
 - pip install pyflakes 
 - pip install pylint 

# Check static code before unit test
before_script:
 - pyflakes . # static code analyze
 - pylint sample.py --disable=missing-docstring # Coding style check

# Run unit test
script: python test_sample.py 

# Build docker image for release artifact
after_success:
 - docker pull python:$docker_image # pull python docker image from officail
 - docker images
 - envsubst < Dockerfile.template > Dockerfile # replace python version tag in Dockerfile
 - docker build -t my_python:$docker_image . # artifact soure code
 - docker images  
 #- docker push my_python:$docker_image # Push or deploy to somewhere


